### ISSUE TITLE
(1.0.4-SNAPSHOT@aar)android.view.InflateException: Binary XML file line #8: Error inflating class com.squareup.timessquare.CalendarPickerView

### ISSUE THREAD

**Issue by itsmechlark** [square/android-times-square#106]
<b>Log</b>

<pre><code>
FATAL EXCEPTION: main android.view.InflateException: Binary XML file line #8: Error inflating class com.squareup.timessquare.CalendarPickerView
            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.createDateView(OfflineDocsFragment.java:383)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.initUIComponents(OfflineDocsFragment.java:375)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.access$800(OfflineDocsFragment.java:103)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment$1.run(OfflineDocsFragment.java:339)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.createDateView(OfflineDocsFragment.java:383)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.initUIComponents(OfflineDocsFragment.java:375)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.access$800(OfflineDocsFragment.java:103)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment$1.run(OfflineDocsFragment.java:339)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/anim/pulltorefresh__slide_in_from_bottom.xml from color state list resource ID #0x7f040001
            at android.content.res.Resources.loadColorStateList(Resources.java:2081)
            at android.content.res.Resources.getColor(Resources.java:761)
            at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:89)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.createDateView(OfflineDocsFragment.java:383)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.initUIComponents(OfflineDocsFragment.java:375)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.access$800(OfflineDocsFragment.java:103)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment$1.run(OfflineDocsFragment.java:339)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: invalid drawable tag translate
            at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:146)
            at android.content.res.ColorStateList.createFromXml(ColorStateList.java:129)
            at android.content.res.Resources.loadColorStateList(Resources.java:2078)
            at android.content.res.Resources.getColor(Resources.java:761)
            at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:89)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.createDateView(OfflineDocsFragment.java:383)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.initUIComponents(OfflineDocsFragment.java:375)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment.access$800(OfflineDocsFragment.java:103)
            at com.cdasia.cdasiaonline.mobile.ui.fragments.OfflineDocsFragment$1.run(OfflineDocsFragment.java:339)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)
</code></pre>

<b>OfflineDocsFragment.java</b>

<pre><code>
private void createDateView() {
        mDatesLayer = (SlidingLayer)mView.findViewById(R.id.sliding_layer_collections);
        LayoutInflater inflater = (LayoutInflater)getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        mDatePickerView = inflater.inflate(R.layout.datepicker__view, null);
        final int bg = getResources().getColor(com.squareup.timessquare.R.color.calendar_bg);
        Log.d(String.valueOf(bg));
        if(mSearchView!=null){
            mDatesLayer.removeAllViews();
            mDatesLayer.addView(mDatePickerView);
            RelativeLayout.LayoutParams rlp = (RelativeLayout.LayoutParams)mDatesLayer.getLayoutParams();
            mDatesLayer.setStickTo(SlidingLayer.STICK_TO_RIGHT);
            if(rlp!=null){
                rlp.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
                rlp.width = RelativeLayout.LayoutParams.MATCH_PARENT;
                rlp.height = RelativeLayout.LayoutParams.MATCH_PARENT;
                mDatesLayer.setLayoutParams(rlp);
                mDatesLayer.setOffsetWidth(0);
            }
        }
    }
</code></pre>

**Comment by KaiWangCanada** [comment]
when using 1.6.3@aar:
08-26 10:40:42.287    8093-8093/kai.kaiprivate E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: kai.kaiprivate, PID: 8093
    java.lang.RuntimeException: Unable to start activity ComponentInfo{kai.kaiprivate/kai.kaiprivate.thirdparty.KaiTimeSquare}: android.view.InflateException: Binary XML file line #7: Error inflating class com.squareup.timessquare.CalendarPickerView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.squareup.timessquare.CalendarPickerView
            at android.view.LayoutInflater.createView(LayoutInflater.java:640)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:449)
            at android.app.Activity.setContentView(Activity.java:2278)
            at kai.kaiprivate.thirdparty.KaiTimeSquare.onCreate(KaiTimeSquare.java:21)
            at android.app.Activity.performCreate(Activity.java:6374)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:614)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:449)
            at android.app.Activity.setContentView(Activity.java:2278)
            at kai.kaiprivate.thirdparty.KaiTimeSquare.onCreate(KaiTimeSquare.java:21)
            at android.app.Activity.performCreate(Activity.java:6374)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: android.content.res.Resources$NotFoundException: File res/layout/abc_action_bar_up_container.xml from color state list resource ID #0x7f040001
            at android.content.res.Resources.twLoadColorStateList(Resources.java:3901)
            at android.content.res.Resources.loadColorStateList(Resources.java:3839)
            at android.content.res.Resources.getColor(Resources.java:2012)
            at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:114)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:614)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:449)
            at android.app.Activity.setContentView(Activity.java:2278)
            at kai.kaiprivate.thirdparty.KaiTimeSquare.onCreate(KaiTimeSquare.java:21)
            at android.app.Activity.performCreate(Activity.java:6374)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag LinearLayout
            at android.content.res.ColorStateList.twCreateFromXmlInner(ColorStateList.java:176)
            at android.content.res.ColorStateList.twCreateFromXml(ColorStateList.java:147)
            at android.content.res.Resources.twLoadColorStateList(Resources.java:3897)
            at android.content.res.Resources.loadColorStateList(Resources.java:3839)
            at android.content.res.Resources.getColor(Resources.java:2012)
            at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:114)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:614)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:449)
            at android.app.Activity.setContentView(Activity.java:2278)
            at kai.kaiprivate.thirdparty.KaiTimeSquare.onCreate(KaiTimeSquare.java:21)
            at android.app.Activity.performCreate(Activity.java:6374)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by ngheungyu** [comment]
@JakeWharton Same issue in 1.6.4, using buildToolsVersion 23
