### ISSUE TITLE
Add isInEditMode checks for preview rendering.

### ISSUE THREAD

**Issue by cs-victor-nascimento** [square/android-times-square#176]
Hey people!

I am trying to use TimesSquare but am getting a NullPointerException in a simple preview from Android Studio like:

![npe_timessquare](https://cloud.githubusercontent.com/assets/7049728/5943537/f1eccb58-a706-11e4-9bbc-70cd343f0a65.png)
Looking through the code it seems a bit strange that it should be working... 

[This code](https://github.com/square/android-times-square/blob/master/library/src/com/squareup/timessquare/MonthView.java#L24) seems like will always throw a null pointer exception but I may be mistaken...

The layout file I am trying to preview is:

``` xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.squareup.timessquare.CalendarPickerView
        android:id="@+id/calendar_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
```
When I run it the app crashes just the same.

Am I missing something? Thanks in advance

**Comment by edenman** [comment]
Are you initializing the calendar?  See the README for an example of calling `init`

**Comment by cs-victor-nascimento** [comment]
Yeah... I missed it... Sorry for the inconvenience!
But that means it won't be able to preview in Studio right?

**Comment by JakeWharton** [comment]
We can add some isInEdit checks for reasonable preview rendering.

**Comment by cs-victor-nascimento** [comment]
That would help :+1:

**Comment by JakeWharton** [comment]
Re-purposed the issue for that task.

**Comment by glebsts** [comment]
Hi :) So, any progress with that? I have problems with previewing layout in AS (did not check eclipse), if there is CalendarPickerView dropped onto layout.

**Comment by glebsts** [comment]
Hello again. Few months ago I just threw away this component. Now took that again, and still proble s with rendering. AS, API17 rendered, gradle imported 1.6.4 version. 
java.lang.IllegalArgumentException: Illegal pattern character 'L'
	at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:845)
	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:659)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:585)
	at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:140)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:458)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:170)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:103)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:190)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:206)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:131)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:746)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:718)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:749)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:718)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:372)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:394)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:337)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:366)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
	at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$6.run(AndroidDesignerEditorPanel.java:480)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Found that in google: https://code.google.com/p/android/issues/detail?id=75940

So how are you guys using this component?

**Comment by edenman** [comment]
@glebsts you're just talking about issues with previewing a `CalendarPickerView` in Android Studio, right?

**Comment by glebsts** [comment]
I am just trying to figure out if something was fixed or is going to be fixed :) Yes, issue with preview in AS.

**Comment by edenman** [comment]
No changes have been made on this issue.  PRs welcome if you really need AS preview (most of us at Square don't use it).

**Comment by glebsts** [comment]
Well, I thought idea is to provide a component that works in any conditions :) You could at least make a note in readme if you put it into public.... or at least make some statements here in github discussions :) Your component is considered the best across the internets, I was hoping you might be interested in keeping perfect reputation :)
So far I work-arounded that by hiding component and setting visibility in run-time, but you know, sometimes it is nice to see how your layout will look like :D
Are you using Eclipse?
