### ISSUE TITLE
1.6.3 with new support library 23.0.0 Resource NotFoundException

### ISSUE THREAD

**Issue by khusravsh** [square/android-times-square#229]
Getting exception when migrating to new version of the lib together with the support library update:

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.Activity}: android.view.InflateException: Binary XML file line #32: Error inflating class com.squareup.timessquare.CalendarPickerView
...
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class com.squareup.timessquare.CalendarPickerView
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
...
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at com.my.Activity.onCreate(Activity.java:158)
...
     Caused by: android.content.res.Resources$NotFoundException: File res/layout/abc_action_bar_up_container.xml from color state list resource ID #0x7f040001
            at android.content.res.Resources.loadColorStateList(Resources.java:2592)
            at android.content.res.Resources.getColor(Resources.java:932)
            at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:114)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag LinearLayout
            at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:148)
            at android.content.res.ColorStateList.createFromXml(ColorStateList.java:131)
            at android.content.res.Resources.loadColorStateList(Resources.java:2588)
            at android.content.res.Resources.getColor(Resources.java:932)
            at com.squareup.timessquare.CalendarPickerView.<init>(CalendarPickerView.java:114)
            at java.lang.reflect.Constructor.newInstance(Native Method)
```

Tried cleaning, rebuilding with Studio and gradle, invalidating caches. If then return to 1.6.2 and 22.2.1, everything is ok.

The stack is trimmed.

**Comment by NeverGivinUp** [comment]
Yes, this seems to be the same exception I get.  @khusravsh's exception refers to a different tag ('LinearLayout' vs. 'alpha'), but the resource ID is the same (#0x7f040001).

The CalendarPickerView line seems to be ``` final int bg = a.getColor(R.styleable.CalendarPickerView_android_background, res.getColor(R.color.calendar_bg));```

As a note: I'm getting it on a Motorola Moto E running Android 4.4.4. What Android version are you running @khusravsh?

**Comment by khusravsh** [comment]
LG Nexus 4, Android 5.1.1. I created a test project, how to upload it?

**Comment by khusravsh** [comment]
there's nothing special about it, though - just a standard studio project with 1 CalendarView inside a RelativeLayout

**Comment by edenman** [comment]
I don't have time to dig into this today but if somebody wants to submit a PR I'll happily review+release.

**Comment by jbaginski** [comment]
seems that when it's included as a project module it works correctly. is it possible that the maven build is corrupted?

**Comment by edenman** [comment]
@jbaginski @khusravsh @NeverGivinUp can one of you check to see if 1.6.4 (just released to maven central) fixes this?

**Comment by khusravsh** [comment]
Have been checking for the last hour when the library will reach repositories. Will try again in a few mins

**Comment by rafaeltoledo** [comment]
Fixed for me.

**Comment by khusravsh** [comment]
The bug is gone. Thank you!

**Comment by edenman** [comment]
Thanks for your patience, all!

**Comment by NeverGivinUp** [comment]
Works for me. Big Thanks to everyone that contributed to this fix :-)

**Comment by freezy** [comment]
Fixed it for me too. Might want to tag 1.6.4 since it doesn't show up under [releases](https://github.com/square/android-times-square/releases) and I assumed 1.6.3 was latest until I came across this issue.

In any case, thanks for the fix!
