### ISSUE TITLE
Xamarin Custom Render with Android-times-square ClassCastException

### ISSUE THREAD

**Issue by CFerndp** [square/android-times-square#257]
Hello,

First for all, i apologize for my english.

I'm try to make a Custom Render in Xamarin.Forms for use Times Square calendar for Android and iOS.
I made this code for Android Custom Render:
```C#
using System;
using Android.Widget;
using Xamarin.Forms.Platform.Android;
using Xamarin.Forms;
using LanguageCenter;
using System.ComponentModel;
using LanguageCenter.Droid;
using Android.App;
using Android.OS;
using Android.Support.V4.View;
using Square.TimesSquare;

[assembly: ExportRenderer(typeof(CalendarViewAdvanced), typeof(CalendarViewRendererAdvanced))]
namespace LanguageCenter.Droid
{
	public class CalendarViewRendererAdvanced : ListViewRenderer
	{
		protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
		{
			base.OnElementChanged(e);

			var appContext = Forms.Context.ApplicationContext;


			if (e.OldElement != null || this.Element == null) {
				return;
			}


			CalendarPickerView calendar = new CalendarPickerView (Forms.Context, null);


			var today = DateTime.Now;
			var nextYear = today.AddYears(1);

			calendar.Init(today, nextYear).WithSelectedDate(today).InMode(CalendarPickerView.SelectionMode.Single);

			SetNativeControl (calendar);
		}  
	}
}
```
The class CalendarViewAdvance extends Xamarin.Forms.ListView.

When i execute this, i see this exception:
````
Java.Lang.ClassCastException: md5afd6673e0ee9440e9d745cae3b1062af.MonthView cannot be cast to com.squareup.timessquare.MonthView
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00063] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:571
  at Android.Views.ViewGroup.Layout (Int32 l, Int32 t, Int32 r, Int32 b) [0x00082] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.ViewGroup.cs:3763
  at Xamarin.Forms.Platform.Android.ViewRenderer`2[TView,TNativeView].OnLayout (Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) [0x00059] in <filename unknown>:0
  at Xamarin.Forms.Platform.Android.ListViewRenderer.OnLayout (Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) [0x00000] in <filename unknown>:0
  at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (IntPtr jnienv, IntPtr native__this, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) [0x00008] in <filename unknown>:0
  at at (wrapper dynamic-method) System.Object:eae702cf-d6f1-4f53-8350-13b611647c22 (intptr,intptr,bool,int,int,int,int)
  at --- End of managed exception stack trace ---
  at java.lang.ClassCastException: md5afd6673e0ee9440e9d745cae3b1062af.MonthView cannot be cast to com.squareup.timessquare.MonthView
  at at com.squareup.timessquare.MonthView.create(MonthView.java:36)
  at at com.squareup.timessquare.CalendarPickerView$MonthAdapter.getView(CalendarPickerView.java:758)
  at at android.widget.AbsListView.obtainView(AbsListView.java:2347)
  at at android.widget.ListView.makeAndAddView(ListView.java:1864)
  at at android.widget.ListView.fillDown(ListView.java:698)
  at at android.widget.ListView.fillFromTop(ListView.java:759)
  at at android.widget.ListView.layoutChildren(ListView.java:1659)
  at at android.widget.AbsListView.onLayout(AbsListView.java:2151)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ListViewRenderer.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ListViewRenderer.onLayout(ListViewRenderer.java:64)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:48)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewContainer.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewContainer.onLayout(ScrollViewContainer.java:61)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at at android.widget.ScrollView.onLayout(ScrollView.java:1502)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.onLayout(ScrollViewRenderer.java:57)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:48)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.NavigationRenderer.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.NavigationRenderer.onLayout(NavigationRenderer.java:46)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout(PlatformRenderer.java:62)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
  at at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at at android.view.View.layout(View.java:15671)
  at at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
  at at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
  at at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
  at at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
  at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
  at at android.view.Choreographer.doCallbacks(Choreographer.java:580)
  at at android.view.Choreographer.doFrame(Choreographer.java:550)
  at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
  at at android.os.Handler.handleCallback(Handler.java:739)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5254)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Somebody can help me??

Thanks for all,

Cristian Fernández.

**Comment by NightlyNexus** [comment]
I'm not familiar with Xamarin at all, but it looks like, somewhere, you are referencing the wrong `MonthView`. Android's layout inflater will require custom Views to declare their fully qualified class names (like `com.squareup.timessquare.MonthView`) in xml layouts, by the way.

**Comment by CFerndp** [comment]
Ok, thank's for all.
