### ISSUE TITLE
Unable to Initialize CalendarPickerView: IllegalStateException

### ISSUE THREAD

**Issue by JRSoftware92** [square/android-times-square#300]
I'm getting an IllegalStateException stating 'Must have at least one month to display. Did you forget to call init()?' when I add a CalendarPickerView to my fragment. I've tried to trace the issue with Log statements, but the issue seems to occur before my initialization logic even occurs. Here are the following methods associated with my initialization:

Fragment Methods
```
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        initializeCalendarView(container);
        return super.onCreateView(inflater, container, savedInstanceState);
    }

    public void initializeCalendarView(ViewGroup container){
        //This Log Statement Never Occurs
        Log.i("HISTORY-FRAGMENT", "initializeCalendarView");
        Date today = new Date(CustomTimeUtils.today());
        Date lastYear = new Date(CustomTimeUtils.lastYear());
        Date nextMonth = new Date(CustomTimeUtils.nextMonth());

        //These Log Statements Never Occur
        Log.d("HISTORY-FRAGMENT", String.format("Today: %s", today.toString()));
        Log.d("HISTORY-FRAGMENT", String.format("Last Year: %s", lastYear.toString()));
        Log.d("HISTORY-FRAGMENT", String.format("Next Month: %s", nextMonth.toString()));

        if(container != null) {
            calendarView = (CalendarPickerView) container.findViewById(R.id.calendar_view_history);
            calendarView.init(lastYear, nextMonth, Locale.US)
                    .withSelectedDate(today);
        }
    }
```

CustomTimeUtils Methods
```
public static long getDate(int typeCode, int value){
        Calendar calendar = Calendar.getInstance();
        calendar.add(typeCode, value);

        return calendar.getTimeInMillis();
    }
public static long today(){
        return getDate(Calendar.DATE, 0);
    }
public static long nextMonth(){
        return getDate(Calendar.MONTH, 1);
    }

    public static long lastYear(){
        return getDate(Calendar.YEAR, -1);
    }
```

I'm stumped as to why this is occurring, as I can't figure out how to trace the problem on my end. Does anybody know why this could be happening, or perhaps a better method to accomplish what I'm trying to do?

EDIT: Full Stack Trace:

```
08-30 16:57:27.431 29638-29638/com.dev.application E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.dev.application, PID: 29638
                                                                      java.lang.IllegalStateException: Must have at least one month to display.  Did you forget to call init()?
                                                                          at com.squareup.timessquare.CalendarPickerView.onMeasure(CalendarPickerView.java:449)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                                          at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:78)
                                                                          at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1132)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:675)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5953)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2685)
                                                                          at android.view.View.measure(View.java:18834)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2131)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1237)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1474)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6100)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
```

**Comment by JakeWharton** [comment]
Full stacktrace please.

**Comment by JRSoftware92** [comment]
I've edited my post to include the full stacktrace of the event

**Comment by JakeWharton** [comment]
If `onMeasure` is being called that means somewhere you're initializing a `CalendarPickerView` and not calling `init()`. Are you sure that piece of code is the problem?

**Comment by JRSoftware92** [comment]
It's the only place in my code where `init()` is called. I'm using AndroidAnnotations as well, which handles initialization of some views on the backend, but I'm not using that to interact with the CalendarPickerView.

**Comment by JRSoftware92** [comment]
Would it make a difference if I initialized the View programmatically? Perhaps the field is being accessed prematurely as a result of the XML element being accessed before I have explicit control.

**Comment by edenman** [comment]
What's the superclass of this fragment?  Fragment.onCreateView returns null and doesn't do any inflation...

**Comment by JRSoftware92** [comment]
The superclass of the fragment is android.support.v4.app.Fragment.

**Comment by edenman** [comment]
how/where are you inflating the layout that includes the CalendarPickerView, then?

**Comment by JRSoftware92** [comment]
That could be the issue. The Layout is inflated by AndroidAnnotations. It might be referencing the View in some way that's causing the error, which is why my log statements are never reached. I'm going to take the time to rework the fragment without AndroidAnnotations, and I'll see if that makes a difference.

**Comment by edenman** [comment]
👍 I'm going to close this out, re-open if you do that and still think there's an ATS bug.

**Comment by VishalJogiya** [comment]
Hi,
I'm Getting the same Exception Here Is My Code.

```
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.squareup.timessquare.CalendarPickerView
        android:id="@+id/calendar_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</ScrollView>
```

```

    private void showDatePicker2() {
        // Inflate your custom layout containing 2 DatePickers
        LayoutInflater inflater = getLayoutInflater();
        View customView = inflater.inflate(R.layout.custom_date_picker, null, false);

        // Define your date pickers

        Calendar nextYear = Calendar.getInstance();
        nextYear.add(Calendar.YEAR, 1);

        final CalendarPickerView calendarPickerView = (CalendarPickerView) customView.findViewById(R.id.calendar_view);

        if (transactionList != null && transactionList.size() > 0) {
            try {
                calendarPickerView.init(new Date(transactionList.get(0).getTransactionDate())
                        , nextYear.getTime())
                        .withSelectedDate(new Date())
                        .inMode(CalendarPickerView.SelectionMode.RANGE);
            } catch (Exception e) {
                Toast.makeText(this, getString(R.string.something_went_wrong), Toast.LENGTH_SHORT).show();
            }
        }
//        calendar.highlightDates(getHolidays());


        // Build the dialog
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setView(customView); // Set the view of the dialog to your custom layout
        builder.setTitle("Select start and end date");
        builder.setPositiveButton(getString(R.string.ok_btn), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {

                ArrayList<Date> dates = (ArrayList<Date>) calendarPickerView.getSelectedDates();
                if (dates != null && dates.size() >= 2) {

                    //Note: delete transactions upto date + m
                    Calendar c = Calendar.getInstance();
                    c.setTimeInMillis(dates.get(0).getTime());

                    c.set(Calendar.HOUR_OF_DAY, 0);
                    c.set(Calendar.MINUTE, 0);
                    c.set(Calendar.SECOND, 0);
                    c.set(Calendar.MILLISECOND, 1);


                    startDate = c.getTimeInMillis();


                    c.setTimeInMillis(dates.get(dates.size() - 1).getTime());


                    //                      HH:MM:SS:milSec
                    //set end date to max 23:59:59:999
                    c.set(Calendar.HOUR_OF_DAY, 23);
                    c.set(Calendar.MINUTE, 59);
                    c.set(Calendar.SECOND, 59);
                    c.set(Calendar.MILLISECOND, 999);

                    endDate = c.getTimeInMillis();

                    Toast.makeText(ReportsActivity.this,
                            "Start Date " + HelperStaticMethods.getFormatedDate(startDate, "dd MMM yyyy")
                                    + "End Date " + HelperStaticMethods.getFormatedDate(endDate, "dd MMM yyyy"), Toast.LENGTH_SHORT).show();
                    reloadAdapter();
                    dialog.dismiss();
                }


            }
        });

        builder.setNegativeButton(getString(R.string.cancel), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {
                dialogInterface.cancel();
            }
        });
        // Create and show the dialog
        builder.create().show();

    }

```

I cant trace it..
Please HElp.
Thanks
