### ISSUE TITLE
crash: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}

### ISSUE THREAD

**Issue by feidi2014** [square/android-times-square#384]
Here is the log

java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
                                                                at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
                                                                at android.widget.TextView.<init>(TextView.java:783)
                                                                at android.widget.TextView.<init>(TextView.java:704)
                                                                at android.widget.TextView.<init>(TextView.java:700)
                                                                at android.widget.TextView.<init>(TextView.java:696)
                                                                at com.squareup.timessquare.DefaultDayViewAdapter.makeCellView(DefaultDayViewAdapter.java:10)
                                                                at com.squareup.timessquare.CalendarRowView.setDayViewAdapter(CalendarRowView.java:87)
                                                                at com.squareup.timessquare.CalendarGridView.setDayViewAdapter(CalendarGridView.java:43)
                                                                at com.squareup.timessquare.MonthView.setDayViewAdapter(MonthView.java:169)
                                                                at com.squareup.timessquare.MonthView.create(MonthView.java:40)
                                                                at com.squareup.timessquare.CalendarPickerView$MonthAdapter.getView(CalendarPickerView.java:846)
                                                                at android.widget.AbsListView.obtainView(AbsListView.java:2363)
                                                                at android.widget.ListView.makeAndAddView(ListView.java:1970)
                                                                at android.widget.ListView.fillDown(ListView.java:704)
                                                                at android.widget.ListView.fillFromTop(ListView.java:765)
                                                                at android.widget.ListView.layoutChildren(ListView.java:1716)
                                                                at android.widget.AbsListView.onLayout(AbsListView.java:2162)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.widget.ScrollView.onLayout(ScrollView.java:1535)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
09-03 22:11:09.289 600-600/com.bz.skipper E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                at android.view.View.layout(View.java:17637)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

please help

**Comment by JakeWharton** [comment]
Without a sample that reproduces the issue we won't be able to help. Based
on the stacktrace, your theme/styles aren't configured appropriately.

**Comment by feidi2014** [comment]
@JakeWharton them/styles for calendar view?

**Comment by feidi2014** [comment]
@JakeWharton  I think there is a problem with this line in DefaultDayViewAdapter
TextView textView = new TextView(
              new ContextThemeWrapper(parent.getContext(), R.style.CalendarCell_CalendarDate));
what is the parent for CalendarCell_CalendarDate style?

**Comment by feidi2014** [comment]
@JakeWharton I realized that this issue happens only when using Appcompat and lollipop (my lollipop device), it doesn't crash on my 6.0 device

and it has something with style, please see Amir Dadgari's answer
https://stackoverflow.com/questions/28523517/appcompat-popup-menu-runtimeexception
 
is it possible for you to change your custom styles by adding parent like he suggested?

**Comment by feidi2014** [comment]
@JakeWharton any thought?

**Comment by ebbnormal** [comment]
@feidi2014 in my case i was applying a custom theme to an AppCompatEditText which was missing an item for a state which needed to be defined, namely:      `<item name="colorControlHighlight"></item>` once I added it to my style, and highlighted the edit field, it no longer crashed with the error you had above.
