### ISSUE TITLE
Support attributes for color selector "tsquare_dayTextColor"

### ISSUE THREAD

**Issue by quentin41500** [square/android-times-square#509]
## Issue

When trying to apply a selector to the property `app:tsquare_dayTextColor="@color/selector_calendar_text"` using custom attributes `?attr/...`, we currently get this error.

I believe this is because of this line [`ColorStateList colors = getResources().getColorStateList(resId);` ](https://github.com/square/android-times-square/blob/7f2f3cabd8d13914e8aa0b910dd89105ec8caf69/library/src/main/java/com/squareup/timessquare/CalendarGridView.java#L55). 

Would we be able to support custom attributes for selectors, maybe using `public ColorStateList getColorStateList(@ColorRes int id, @Nullable Theme theme)`?

Anything I'm missing in order to do this?

## Example

```       
 <com.squareup.timessquare.CalendarPickerView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tsquare_dayTextColor="@color/selector_calendar_text" <---- This />
```

```
<selector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:color="?textSelected" android:state_selected="true" />
    <item android:color="?textSelected" android:state_pressed="true" />
     <item android:color="?textDisabled" app:tsquare_state_selectable="false" />
     <item android:color="?textDefault" />
</selector>

```

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <attr name="textDefault" format="color" />
    <attr name="textDisabled" format="color" />
    <attr name="textSelected" format="color" />
</resources>
```

```
    <style name="MyTheme">

        <!-- Global Text -->
        <item name="textDefault">#000000</item>
        <item name="textDisabled">#CCCCCC</item>
        <item name="textSelected">#FFFFFFFF</item>

    </style>
```

## Stacktrace

```
2022-01-14 17:00:34.476 29382-29382/com.myproject.ui W/Resources: ColorStateList com.myproject.ui:color/selector_calendar_text has unresolved theme attributes! Consider using Resources.getColorStateList(int, Theme) or Context.getColorStateList(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getColorStateList(Resources.java:1097)
        at com.squareup.timessquare.CalendarGridView.setDayTextColor(CalendarGridView.java:55)
        at com.squareup.timessquare.MonthView.setDayTextColor(MonthView.java:183)
        at com.squareup.timessquare.MonthView.create(MonthView.java:56)
        at com.squareup.timessquare.CalendarPickerView$MonthAdapter.getView(CalendarPickerView.java:909)
        at android.widget.AbsListView.obtainView(AbsListView.java:2387)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
        at android.widget.ListView.onMeasure(ListView.java:1323)
        at com.squareup.timessquare.CalendarPickerView.onMeasure(CalendarPickerView.java:538)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
```

**Comment by quentin41500** [comment]
Here is a working example with a solution: https://github.com/quentin41500/android-times-square/commit/f17075f65cd34763cfb70d278155b6bb98686a95
